### ISSUE TITLE
Compilation failure with hdk 0.0.47-alpha1

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-rust#2187]
Been trying to upgrade and am hitting this. Build caches cleared etc, all the usual suspects seem to be fine...

```
error[E0433]: failed to resolve: could not find `document_join_macro` in `futures_util`
   --> /home/pospi/projects/holo-rea/oce-holo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:561:15
    |
561 | futures_util::document_join_macro! {
    |               ^^^^^^^^^^^^^^^^^^^ could not find `document_join_macro` in `futures_util`

error[E0433]: failed to resolve: could not find `document_select_macro` in `futures_util`
   --> /home/pospi/projects/holo-rea/oce-holo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:584:15
    |
584 | futures_util::document_select_macro! {
    |               ^^^^^^^^^^^^^^^^^^^^^ could not find `document_select_macro` in `futures_util`

error: aborting due to 2 previous errors
```

**Comment by zippy** [comment]
This is due to an upstream dependency change that our pinning couldn't guard against.  Fixed in https://github.com/holochain/holochain-rust/pull/2188

**Comment by pospi** [comment]
Hmm. I was running on `0.0.48-alpha1` for a while and ended up giving up on it due to some performance issues with conductor init... now I've gone back to `0.0.42-alpha5` and am hitting this error again!

Have run the `hn-flush` command and rebooted, issue still persists... not sure what else I could try to troubleshoot? Looks like `0.0.49-alpha1` is just `0.0.47-alpha1` with the futures fix, and I got a lot of test breakages with that release due to link ordering changing... but maybe I should give it a go?

**Comment by pospi** [comment]
`0.0.49-alpha1` does seem to be looking better... at least it compiles, and the delay on starting new conductors seems to be reduced somewhat. Probably fine dealing with it for now (:
